### ISSUE TITLE
M4b format not recognized

### ISSUE THREAD

**Issue by gardiol** [gateship-one/odyssey#138]
Files in m4b format are not listed as supported and cannot be played. I have a lot of audio books in this format.

**Comment by gnome17** [comment]
Hi,
thanks for your feedback. 
We support all formats that are listed here
https://developer.android.com/guide/topics/media/media-formats.html

But like with .opus we noticed that some containers are not listed but still supported so I guess we will check if m4b works and then add it to the supported list so that you can access it via our file browser.

**Comment by gardiol** [comment]
Thank you... I think too it should work, I will wait for a next version!

**Comment by gnome17** [comment]
Hey,
we just released a new version of odyssey (1.1.14) which contains support for m4b via our file browser. It is already available at Google Play and will be available on F-Droid in the next few days we think.
