### ISSUE TITLE
+ icon is not responding in odyssey music player 

### ISSUE THREAD

**Issue by mohail** [gateship-one/odyssey#144]
#### Expected behavior
+icon which is there for the addition of new songs in odyssey music player should work and we should be able to add songs to album

#### Actual behavior
When we go to the albums and click on the + icon a pop-up message reflects on screen showing please wait and then nothing happens further. 
#### How to reproduce

- Go to the odyssey music player and click on the option for albums  
![Screenshot_2018-03-28-10-12-06-922_org.gateshipone.odyssey.png](https://cdn.utopian.io/posts/05ffa4a1839bc8e1c9199d49b3f0596df87dScreenshot_2018-03-28-10-12-06-922_org.gateshipone.odyssey.png)
- Click on any one of the albums in your filder
- you will find + icon at the top right corner of the app 

- click on the icon and you will find the icon is not responding

* Browser: Odyssey new version 1.1.13
* Operating system: Android 6 redmi 4

#### Recording Of The Bug
https://youtu.be/VVoJ7aL8vnU
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mohail/icon-is-not-responding-in-odyssey-music-player">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by djselbeck** [comment]
As said in other issues and already in the FAQ we ignore everything from Utopian.io

**Comment by diegopucci** [comment]
Hello @djselbeck CEO of Utopian here. I've found this comment and was wondering why you have decided to ignore any issue coming from our platform. We are trying our best to provide Open Source projects with a genuine community of Open Source contributors and your feedback is important for us, to understand what we may be doing wrong. We have recently stopped pushing issues to github for projects that did not opt-in. So you won't receive them any longer, still for us your feedback has huge value and I'd be glad if you could get back to me with your suggestions. Thanks for your time

**Comment by djselbeck** [comment]
Hello @diegopucci, thank you for taking the time to explain your point of view here. The problem is that I don't think our two projects need another shadow community besides the already very active and very helpful community. Open source never needed a service like Utopian before and thrived anyway. Gateship One's projects are developed in the spare time of my and a colleague of mine as a hobby and we don't have any interest in gaining anything from the projects besides fun and personal use of the applications. We also don't accept donations for our own. 

Besides ideological doubts so far the projects of Gateship One only received wrong issues that were no bugs but misuse of the applications from Utopian.

**Comment by diegopucci** [comment]
@djselbeck thanks for your valuable feedback. We are trying to build a community which does Open Source contributiona for passion while accessing stable funds for growth. We do understand this is not necessarly welcome by everyone and that's the reason why we have decided to allow only projects that did optin. As for wrong issues you got, I am sorry for that. We are trying to filter out misuses but the amount of submitted issues was so high we may have missed some. Thabks for your feedback again and good luck with your projects!
