### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Primokorn** [gateship-one/odyssey#2]
Hi,

Thanks for this new FLOSS music player!
I have a few feature requests. I hope it's OK to open only one thread.

### Playilst
• Add to playlist doesn't work. The menu Playlist is empty.
• Multi-selection to add several tracks in one go.

### Library
• Automatically rescan the storage when opening Odyssey or add a feature in the settings for a manual rescan
• Play the next track when the current one is finished

### Speed
• Add a feature to control the playback speed (important on my side when listening to podcasts)

Good luck with Odyssey!
Thanks.

**Comment by djselbeck** [comment]
Hello thanks for your feedback. It is ok for us to open multiple requests in one.

Add playlist actually adds songs/artists/albums to the queue of songs that will be played. Not like a saved playlist.

Multi-selection is something we will add in the future.

The rescan of the music library sadly is not possible anymore because android prohibits the use of the corresponding Intent by user applications. 

"Play the next track when the current one is finished" - Sorry ;) we don't quite understand this. If you play an album/artist or folder all tracks from it are enqueued and will be played sequentially. Only if you select one track from the "all tracks" view the only track is enqueued for perfomance reasons. 

Playback speed - We will have a look into this but can't make any promises.

As for an ETA we are currently in the process of merging our artwork support in the master branch to add the ability to download artwork from the internet. After this we'll check your requests.

Thanks again for your input, it is very helpful to get new perspectives.

**Comment by Primokorn** [comment]
Thanks for your answers.

Actually I'd like to use your app to listen to audio podcasts. I don't need a playlist by album/author but I want the app to play all songs/files one after the other from the "all tracks" view.
Why it can't be done for performance reasons? AFAIK all players I tried have this feature.

Too bad for the rescan since this forces us to reboot each time we remove/add new files. What do you mean by "Android prohibits"? VLC automatically rescan the library when launching the app for example.

About the playback speed, it's very useful for podcasts. FYI VLC also has this feature.

Thanks again!

**Comment by djselbeck** [comment]
You can play all the tracks from the alltracks view. Just hit the floating play button at the right bottom corner. This will enqueue all tracks and then play them. You can then swipe the nowplaying view up and select a track from the playlist queue. 

Unfortunately VLC uses its own database and not the system provided one. Which for your case is probably good but is horrible for large database. I'm using a 200gb microsd with like 23000 music files ;)

**Comment by gnome17** [comment]
Closed.
See #13 and #14 .
