### ISSUE TITLE
"Disc Number" tag not being read.

### ISSUE THREAD

**Issue by foldfree** [gateship-one/odyssey#210]
# Bug Report

## Setup Description
lineageos
### Version of Odyssey
1.1.20 from f-droid
### Android Version
10 
### Device Manufacturer and model
Xiaomi willow
## Bug Description
Release with multiple discs are not properly formatted.
### Description

When playing a release with multiple discs. Files are in such order :

1 -track 1 of disc 1
1 - track 1 of disc 2
1 - track 1 of disc 3
2 - track 2 of disc 1
2 - track 2 of disc 2
2 - track 2 of disc 3

That's because the ID tag $DISC_NUMBER is ignored.

### Expected Behaviour

1 - track 1 disc 1
2 - track 2 disc 1
3 - track 3 disc 1
1 - track 1 disc 2
2 - track 2 disc 2
3 - track 3 disc 2
1 - track 1 disc 3
Etc...

###Note
Most android music players have this bug. Only Vanilla got it right as far as I know.

**Comment by gnome17** [comment]
Hi,

from what we can tell this is a problem of android 10 itself. I noticed the issue after I upgraded my phone from 9 to 10.

I can reproduce it in an android 10 emulator but it doesn't appear on an android 11 emulator. So far it seems to me that android 10 introduced some kind of buggy behavior which resulted in the loss of the disc information.

We have no solution for this. As a workaround we introduced the option to sort songs of an album by their filename. This is available in the options of odyssey. 

This is just a workaround and will require that your files are named properly in order to work.

**Comment by foldfree** [comment]
Thanks, I'll wait for my phone to have an android 11 ROM then. I didn't know it was an android 10 specific issue.

I understand your time is limited, your music player is the best one I found so far. I am submitting issues because I love this app, not the opposite :)

**Comment by foldfree** [comment]
I have updated my phone to A11 and can confirm this issue is gone
