### ISSUE TITLE
Automatic audio files tagging using MusicBrainz / Picard API.

### ISSUE THREAD

**Issue by GamePlayer-8** [gateship-one/odyssey#268]
# Feature request

Hello,

Would it be possible to automatically tag the untagged audio files using MusicBrainz / Picard API?
Currently Picard software works on desktop platforms rather than on Android.

**Comment by gnome17** [comment]
Hi,

sorry but it's not likely we will ever do this because of several reasons but the most important one is that we are not willing to edit any file on your phone that was not created by odyssey before. This is mainly because the restrictions google enforces for apps that do such a thing.

So the only option would be that we create our own media database and allow you to edit your music there. But this is a lot of work and most likely not what you had in mind.

**Comment by GamePlayer-8** [comment]
would it be possible then to provide some plugin interface / api for modding the app without recompilling?
