### ISSUE TITLE
Album with disc number appears separately from one without

### ISSUE THREAD

**Issue by mjbogusz** [gateship-one/odyssey#46]
Album with tracks where some have 'disc number' set to 1 and others have the tag empty doesn't get merged and appears as doubled album on the list (though with only tracks respectively with or without that tag inside these albums).

Probably one entry is for 'Album Name' and other one for 'Album Name, disc 1', however the 'disc X' part is not displayed.

A (simple) solution would be to default unset disc number to '1'.
Additionally, deciding whether to display disc number at all based on total number of discs (i.e. `if(total_number_of_discs>1){}`) would be nice (though it would rather belong to track list).

**Comment by djselbeck** [comment]
The Android mediascanner reads the Disc no. tag. This is the only tag that should be used to indicate the disc number.  Odyssey just parses the disc no parts of the android database track no column(this is a bit weird as android stores discno and trackno in one column like ddtt where dd is the disc no and tt is the track no). So if Android detects an album as two so does odyssey because we only identify albums via a unique tag per album. 

If you use non-standard conventions on naming multiple discs of the same album you can't expect software to identify this as there is no reliable way to do so.

I recommend that you retag your music with [MusicBrainz Picard](https://picard.musicbrainz.org/) as it is very easy to use and it produces a nicely ordered and very consistent tagged library.

**Comment by mjbogusz** [comment]
The album tag was used correctly and contained only album name, but some files/tracks had their 'disk number' tag set while others did not and these 2 groups got listed under separate though seemingly identical albums.

I have since unified the tags (I have no idea how they ended up like that) using desktop Foobar, but I had to dig in a bit to find the reason for this behaviour. If Android's media database reports them separately, there's not much to do, but wouldn't it be possible to display disc number (if any) with track number, e.g. as "dd.tt"? This would be nice to have for multi-disc albums and would act as an indicator for situations like one I've encountered.

**Comment by djselbeck** [comment]
> If Android's media database reports them separately, there's not much to do, but wouldn't it be possible to display disc number (if any) with track number, e.g. as "dd.tt"? This would be nice to have for multi-disc albums and would act as an indicator for situations like one I've encountered.

Yes this should be possible. I think the sibling MALP already does this

**Comment by gnome17** [comment]
We will now display the disc and tracknumber in the format dd.tt if the related album contains more than one disc. 

This feature is implemented with commit f75d5c8 and will be released with the next version.
