### ISSUE TITLE
Tracks page - Move track no.

### ISSUE THREAD

**Issue by gsantner** [gateship-one/odyssey#57]
Please move track number somewhere else (e.g. to the right/end side) to make it easier to recognize tracks. The current way - to display in front of track title is uncommon and makes it harder to read/to find what looking for.

Just as example:
<table><tr>
<td>Current<img src="https://cloud.githubusercontent.com/assets/6735650/24019948/6d204446-0a9a-11e7-9b8b-784d2728cfab.png"></td>
<td>Afterw?<img src="https://cloud.githubusercontent.com/assets/6735650/24019964/829a4e3e-0a9a-11e7-8633-d859f15e4921.png"></td>
</tr></table>
--> Second better readable

If you don't want this default, please allow to enable it via option.

**Comment by djselbeck** [comment]
Frankly I've never ever seen this layout in an application. And I find it really confusing. Your example is misleading because it shows only tracks beginning with numbers.

Implementing this as an option is also not a way I would like to go because as it is odyssey already provides too many options IMHO and it really shouldn't be more cluttered.

**Comment by gsantner** [comment]
Maybe yeah because I created the screenshot in top of song list. But also for other tracks. 
So as you also find it confusing, do you think of moving it?

**Comment by gnome17** [comment]
Hi, it seemed that you missunderstand my colleague. We found your solution quite confusing and for the moment we have no plans to change the position of the track number.

**Comment by gsantner** [comment]
Oh. Well, maintaining a local fork should be enough for now.
