### ISSUE TITLE
[FR][UX] jump to album / artist

### ISSUE THREAD

**Issue by ildar** [gateship-one/odyssey#77]
Ux needs some polishing. I like ux of Apollo and guess that its popularity is exactly because of the great ux.
One trick is on the Current track screen: tapping on the top label with track's Artist+Album brings you to the Album, next tap navigates you to the Artist.
Please implement. Thanks!
I'm in process of transition from Shuttle to Odyssey.  60% of the way is completed!

**Comment by djselbeck** [comment]
Text labels are not really optimal to be misused as buttons. I would not call this good UX design.

For now you can reach the artist/album from the current playlist with a long press on the current track

**Comment by ildar** [comment]
No problem with labels/not-labels. I just wish I could reach the current
album/artist from the current track view.
Even from the menu in top right corner would be fine.

**Comment by madeindjs** [comment]
It may be a great feature! Is someone have some news about it?

**Comment by djselbeck** [comment]
I don't like the idea because: 

 * Text labels should not be misused as hidden buttons
 * The label is also scrolling if the text is too long which would make the clickable label even more confusing.
 * The option in the top menu would be redundant to the context menu of playlist tracks (which I use for this feature quite often) - also the menu is very long as it is.

Therefore I don't see any reason to change this.

**Comment by ildar** [comment]
But artist/album are still unavailable from the player view, only from
playlist. Tridot menu is still quite empty.

**Comment by madeindjs** [comment]
@djselbeck I am agrre with you there also a way to do this in *context menu* in *playlist view*. But @ildar idea make sense because *Tridot menu* is still quite empty. 

It is a little funny because in *Tridot menu* in *Player View* there are two existing items for Wikipedia:

* Wikipedia
  * Open Album
  * Open Artists

Why not just add something like this 

* Go to  ..
  * Artist
  * Album
  * Folder

**Comment by djselbeck** [comment]
The point is, that you gain nothing:

 - Menu->Jump to->Album (3 clicks)
 - Playlist->Hold click->Album (3 clicks)

The menu may look non cluttered at the moment. But it is longer if playlist is active (all the time on tablets). And also we trying to keep the UIs of both MALP and Odyssey as synchronized as possible. And the MALP menu is really long.
