### ISSUE TITLE
Local album covers not displayed

### ISSUE THREAD

**Issue by b3** [gateship-one/odyssey#98]
I am using the 1.1.6 release available on FDroid on a Motorola G 4G (xt1039) running Android 5.1.

All my music is stored locally on the external SD card.

All albums are stored in their own directory. It consists of flac, ogg and mp3 files. Almost all of them include the cover in the file itself as well as in a file called AlbumArt.jpg inside the album directory.

No cover are show in the Album view. Some pictures are shown in the Artist view but I guess they have been downloaded dynamically.

Any clue?

**Comment by gnome17** [comment]
Hi,
as mentioned in #91 we retrieve the images from the android media database. 

My first guess there are images in the database but could not load properly. In that case no images will be downloaded and no image will be shown.

But it's really hard to tell what kind of problem you are facing. Have you another app that loads images from the media database? Are your files properly tagged?

**Comment by gnome17** [comment]
Close due to inactivity.

**Comment by jesus2099** [comment]
I have same problem.
My files have cover art in their tags but they are not displayed by Odyssey, who just displays a black square.

Only the files without covers have a cover in Odyssey, actually.

I tried almost all options including one called Local Something, even MusicBrainz that does contain a cover art did not work (there is no MBID in my files, I thought Odyssey would do a name match, as artist and album names match 100%).

But music player should display, without changing any setup, by order of priority:

1. Cover art inside file tags
2. Cover art file inside same folder as sound files
3. Online downloads

For online downloads, instead of choosing only one with radio buttons, we should be able to move them around to set of priority (3a, 3b, 3c, etc.).

What is the Android Media Database and how can we make it up to date?

I am using [Sony Music Centre](https://vssupport.sony.net) as my music player and it does display my cover arts contains in files.

**Comment by hellpe** [comment]
I'm having a similar issue: all of my album art is embedded into my music files (mostly using Picard), themselved stored in an SD card, but no cover art is displayed at all on Odyssey.

Like @jesus2099 asked before, I don't know how to add any cover art to the Android media database. VLC and YouTube Music can display my cover art fine.
